CREATE TABLE campaigns
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    trigger_tag VARCHAR(255)                            NOT NULL,
    template_id BIGINT                                  NOT NULL,
    active      BOOLEAN                                 NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    version     BIGINT,
    CONSTRAINT pk_campaigns PRIMARY KEY (id)
);