CREATE TABLE template_variables
(
    template_id   BIGINT       NOT NULL,
    default_value VARCHAR(255),
    variable_name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_template_variables PRIMARY KEY (template_id, variable_name)
);

CREATE TABLE templates
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    subject     VARCHAR(255)                            NOT NULL,
    content     TEXT                                    NOT NULL,
    description VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    version     BIGINT,
    CONSTRAINT pk_templates PRIMARY KEY (id)
);

ALTER TABLE template_variables
    ADD CONSTRAINT fk_template_variables_on_email_template FOREIGN KEY (template_id) REFERENCES templates (id);