server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**, /api/users/**
          filters:
            - RewritePath=/api/auth(?<segment>/?.*), /api/v1/auth${segment}
            - RewritePath=/api/users(?<segment>/?.*), /api/v1/users${segment}

        - id: contact-service
          uri: lb://contact-service
          predicates:
            - Path=/api/contacts/**
          filters:
            - RewritePath=/api/contacts(?<segment>/?.*), /api/v1/contacts${segment}

        - id: campaign-service
          uri: lb://campaign-service
          predicates:
            - Path=/api/campaigns/**
          filters:
            - RewritePath=/api/campaigns(?<segment>/?.*), /api/v1/campaigns${segment}

        - id: template-service
          uri: lb://template-service
          predicates:
            - Path=/api/templates/**
          filters:
            - RewritePath=/api/templates(?<segment>/?.*), /api/v1/templates${segment}

        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/api/emails/**, /t/**, /t/click/**
          filters:
            - RewritePath=/api/emails(?<segment>/?.*), /api/v1/emails${segment}
