server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://db:5432/mailflow
    driver-class-name: org.postgresql.Driver
    username: mailflow
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

