server:
  port: 8089

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:./mailflow-config
        git:
          uri: https://github.com/HMZElidrissi/mailflow-config
          default-label: main
          clone-on-start: true
          timeout: 5
          force-pull: true
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
